# Capa de Cómputo: Define el sistema operativo [cite: 8]
FROM mcr.microsoft.com/devcontainers/python:3.11 [cite: 17]

# Instalamos herramientas de sistema y el cliente de PostgreSQL [cite: 18]
RUN apt-get update && apt-get install -y htop tree postgresql-client [cite: 18]
