# Usamos la imagen base de Python 3.11 de Microsoft
FROM mcr.microsoft.com/devcontainers/python:3.11

# Instalamos htop (monitor de sistema) y tree (visualizador de carpetas)
RUN apt-get update && apt-get install -y htop tree postgresql-client
